---
- name: Manage MySQL Installation and Configuration
  hosts: server
  become: yes
  vars_files:
    - vars.yml
    - secrets.yml
  tasks:
    - name: Remove Mysql conf
      ansible.builtin.apt:
        name:
          - mysql-server
          - mysql-client
          - mysql-common
          - mysql-server-core-*
          - mysql-client-core-*
        state: absent
        purge: yes
        update_cache: yes

    - name: Autoremove and Clean Up
      ansible.builtin.shell:
        cmd: |
          sudo apt-get autoremove -y
          sudo apt-get autoclean -y

    - name: Remove MySQL Configuration and Data
      ansible.builtin.file:
        path: "{{ item }}"
        state: absent
      loop:
        - /etc/mysql
        - /var/lib/mysql

    - name: Install MySQL
      ansible.builtin.apt:
        name: mysql-server
        update_cache: yes
        cache_valid_time: 3600
        state: present

    - name: Start MySQL service
      ansible.builtin.service:
        name: mysql
        state: restarted
        enabled: yes

    - name: Ensure /etc/mysql directory exists
      ansible.builtin.file:
        path: /etc/mysql
        state: directory

    - name: Ensure /etc/mysql/mysql.cnf is delete
      ansible.builtin.file:
        path: /etc/mysql/mysql.cnf
        state: absent

    - name: Enable configuration
      ansible.builtin.template:
        src: ../../templates/my.cnf.j2
        dest: /etc/mysql/my.cnf

    - name: Start MySQL service
      ansible.builtin.service:
        name: mysql
        state: restarted
        enabled: yes

    - name: Update MySQL root password for all root accounts
      community.mysql.mysql_user:
        name: root
        host: "{{ item }}"
        password: "{{ mysql_root_password }}"
        check_implicit_admin: yes
        priv: "*.*:ALL,GRANT"
      with_items:
        - "{{ server_hostname }}"
        - 127.0.0.1
        - ::1
        - localhost

    - name: Create a new database
      community.mysql.mysql_db:
        name: "{{ mysql_database }}"
        state: present
        login_user: "{{ mysql_user }}"
        login_password: "{{ mysql_root_password }}"